language: "node_js"
node_js:
  - "4"
  - "5"
  - 'lts/boron'
  - 'lts/carbon'
  - 'lts/*'

before_install:
  - "npm install make-node@0.3.x -g"
  - "preinstall-compat"

script:
  - "make test-cov"

after_success:
  - "make report-cov"

sudo: false
